[package]
name = "ble_temp"
version = "0.1.0"
authors = ["Aurélien Rivet <aurelienrivet@hotmail.fr>"]
edition = "2018"

[dependencies]
btleplug = "0.4.1"
dbus = "0.8.2"
#btleplug = { path = "../btleplug" }
